from __future__ import annotations

import argparse
import os
import time
from pathlib import Path

import numpy as np

import shade_new20 as shade
from original12_branching import BRANCHES, BranchSpec
from problem_v2_spec import BOUNDS_V2, INPUT_COLS_V2


PROJECT_ROOT = Path(__file__).resolve().parent.parent


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--backend", choices=["avl", "mlp"], required=True)
    p.add_argument("--outdir", type=str, default="")
    p.add_argument("--model-dir", type=str, default="models/aero_mlp_v2")
    p.add_argument("--cores", type=int, default=int(os.environ.get("OPT_CORES", "10")))
    p.add_argument("--epsilon", type=float, default=float(os.environ.get("BRANCH_EPSILON", "0.0031")))
    p.add_argument("--init-dir", type=str, default="shared_branch_initial_populations_v2")
    p.add_argument("--n-per-branch", type=int, default=140)
    return p.parse_args()


def base_bounds() -> np.ndarray:
    return np.asarray([BOUNDS_V2[c] for c in INPUT_COLS_V2], dtype=float)


def branch_bounds(branch: BranchSpec) -> np.ndarray:
    bounds = base_bounds()
    bounds[INPUT_COLS_V2.index("a_S_rel")] = branch.a_s_range
    bounds[INPUT_COLS_V2.index("scheme_fuse")] = [branch.scheme_fuse, branch.scheme_fuse]
    bounds[INPUT_COLS_V2.index("scheme_vertical")] = [branch.scheme_vertical, branch.scheme_vertical]
    bounds[INPUT_COLS_V2.index("a_dihedral_mag")] = branch.a_dihedral_range
    fixed_h = os.environ.get("NEW20_FIXED_H", "").strip()
    if fixed_h:
        h_val = float(fixed_h)
        bounds[INPUT_COLS_V2.index("H")] = [h_val, h_val]
    return bounds


def selected_branches():
    only = os.environ.get("ONLY_BRANCHES", "").strip()
    if not only:
        return BRANCHES
    wanted = {x.strip() for x in only.split(",") if x.strip()}
    return [b for b in BRANCHES if b.name in wanted]


def main() -> None:
    args = parse_args()
    os.environ["NEW20_BACKEND"] = args.backend
    outdir = Path(args.outdir or f"gen_{args.backend}_new20_12branches")
    if not outdir.is_absolute():
        outdir = PROJECT_ROOT / outdir
    outdir.mkdir(parents=True, exist_ok=True)
    init_dir = Path(args.init_dir)
    if not init_dir.is_absolute():
        init_dir = PROJECT_ROOT / init_dir

    manifest = ["branch,backend,initial_population,output_dir"]
    start = time.time()
    print(f"RUNNING NEW20 12-BRANCH {args.backend.upper()} OPTIMIZATION")
    print(f"Output : {outdir}")
    print(f"Cores  : {args.cores}")
    print(f"Init   : {init_dir}")

    for branch in selected_branches():
        des_var = branch_bounds(branch)
        init_pop = init_dir / f"{branch.name}_initial_population_{args.n_per_branch}.npy"
        os.environ["SHADE_INIT_POP_OVERRIDE"] = str(args.n_per_branch)
        if init_pop.exists():
            os.environ["SHADE_INITIAL_POP"] = str(init_pop)
        else:
            os.environ.pop("SHADE_INITIAL_POP", None)
        branch_out = outdir / branch.name
        print(f"\nBRANCH {branch.name}")
        print(f"Initial population: {os.environ.get('SHADE_INITIAL_POP', '[generated by SHADE]')}")
        print(f"a_dihedral_mag bounds: {branch.a_dihedral_range[0]}..{branch.a_dihedral_range[1]}")
        shade.SHADE_algorithm(
            des_var,
            const=2,
            epsilon=args.epsilon,
            gen_path=str(branch_out),
            cores=args.cores,
            model_dir=args.model_dir if args.backend == "mlp" else None,
        )
        manifest.append(f"{branch.name},{args.backend},{os.environ.get('SHADE_INITIAL_POP', '')},{branch_out}")

    (outdir / "manifest.csv").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"TOTAL TIME: {time.time() - start:.2f}s")


if __name__ == "__main__":
    main()
